RESPONSES = [
    (
        {
            "Success": False,
            "Message": "Amount is required"
        },
        400
    ),
    (
        {
            "Model": {
                "TransactionId": 891463508,
                "PaReq": "+/eyJNZXJjaGFudE5hbWUiOm51bGwsIkZpcnN0U2l4IjoiNDI0MjQyIiwiTGFzdEZvdXIiOiI0MjQyIiwiQW1vdW50IjoxMDAuMCwiQ3VycmVuY3lDb2RlIjoiUlVCIiwiRGF0ZSI6IjIwMjEtMTAtMjVUMDA6MDA6MDArMDM6MDAiLCJDdXN0b21lck5hbWUiOm51bGwsIkN1bHR1cmVOYW1lIjoicnUtUlUifQ==",
                "GoReq": None,
                "AcsUrl": "https://demo.cloudpayments.ru/acs",
                "ThreeDsSessionData": None,
                "IFrameIsAllowed": True,
                "FrameWidth": None,
                "FrameHeight": None,
                "ThreeDsCallbackId": "7be4d37f0a434c0a8a7fc0e328368d7d",
                "EscrowAccumulationId": None
            },
            "Success": False,
            "Message": None
        },
        401
    ),
    (
        {
            "Model": {
                "ReasonCode": 5051,
                "PublicId": "pk_**********************************",
                "TerminalUrl": "http://test.test",
                "TransactionId": 891583633,
                "Amount": 10,
                "Currency": "RUB",
                "CurrencyCode": 0,
                "PaymentAmount": 10,
                "PaymentCurrency": "RUB",
                "PaymentCurrencyCode": 0,
                "InvoiceId": "1234567",
                "AccountId": "user_x",
                "Email": None,
                "Description": "Оплата товаров в example.com",
                "JsonData": None,
                "CreatedDate": "/Date(1635154784619)/",
                "PayoutDate": None,
                "PayoutDateIso": None,
                "PayoutAmount": None,
                "CreatedDateIso": "2021-10-25T09:39:44",
                "AuthDate": None,
                "AuthDateIso": None,
                "ConfirmDate": None,
                "ConfirmDateIso": None,
                "AuthCode": None,
                "TestMode": True,
                "Rrn": None,
                "OriginalTransactionId": None,
                "FallBackScenarioDeclinedTransactionId": None,
                "IpAddress": "123.123.123.123",
                "IpCountry": "CN",
                "IpCity": "Beijing",
                "IpRegion": "Beijing",
                "IpDistrict": "Beijing",
                "IpLatitude": 39.9289,
                "IpLongitude": 116.3883,
                "CardFirstSix": "400005",
                "CardLastFour": "5556",
                "CardExpDate": "12/25",
                "CardType": "Visa",
                "CardProduct": None,
                "CardCategory": None,
                "EscrowAccumulationId": None,
                "IssuerBankCountry": "US",
                "Issuer": "ITS Bank",
                "CardTypeCode": 0,
                "Status": "Declined",
                "StatusCode": 5,
                "CultureName": "ru",
                "Reason": "InsufficientFunds",
                "CardHolderMessage": "Недостаточно средств на карте",
                "Type": 0,
                "Refunded": False,
                "Name": "CARDHOLDER NAME",
                "Token": "tk_255c42192323f2e09ea17635302c3",
                "SubscriptionId": None,
                "GatewayName": "Test",
                "ApplePay": False,
                "AndroidPay": False,
                "WalletType": "",
                "TotalFee": 0
            },
            "Success": False,
            "Message": None
        },
        5051
    ),
    (
        {
            "Model": {
                "ReasonCode": 0,
                "PublicId": "pk_********************************",
                "TerminalUrl": "http://test.test",
                "TransactionId": 891510444,
                "Amount": 10,
                "Currency": "RUB",
                "CurrencyCode": 0,
                "PaymentAmount": 10,
                "PaymentCurrency": "RUB",
                "PaymentCurrencyCode": 0,
                "InvoiceId": "1234567",
                "AccountId": "user_x",
                "Email": None,
                "Description": "Оплата товаров в example.com",
                "JsonData": None,
                "CreatedDate": "/Date(1635150224630)/",
                "PayoutDate": None,
                "PayoutDateIso": None,
                "PayoutAmount": None,
                "CreatedDateIso": "2021-10-25T08:23:44",
                "AuthDate": "/Date(1635150224739)/",
                "AuthDateIso": "2021-10-25T08:23:44",
                "ConfirmDate": None,
                "ConfirmDateIso": None,
                "AuthCode": "A1B2C3",
                "TestMode": True,
                "Rrn": None,
                "OriginalTransactionId": None,
                "FallBackScenarioDeclinedTransactionId": None,
                "IpAddress": "123.123.123.123",
                "IpCountry": "CN",
                "IpCity": "Beijing",
                "IpRegion": "Beijing",
                "IpDistrict": "Beijing",
                "IpLatitude": 39.9289,
                "IpLongitude": 116.3883,
                "CardFirstSix": "411111",
                "CardLastFour": "1111",
                "CardExpDate": "11/25",
                "CardType": "Visa",
                "CardProduct": "C",
                "CardCategory": "Visa Signature (Signature)",
                "EscrowAccumulationId": None,
                "IssuerBankCountry": "RU",
                "Issuer": "CloudPayments",
                "CardTypeCode": 0,
                "Status": "Authorized",
                "StatusCode": 2,
                "CultureName": "ru",
                "Reason": "Approved",
                "CardHolderMessage": "Оплата успешно проведена",
                "Type": 0,
                "Refunded": False,
                "Name": "CARDHOLDER NAME",
                "Token": "0a0afb77-8f41-4de2-9524-1057f9695303",
                "SubscriptionId": None,
                "GatewayName": "Test",
                "ApplePay": False,
                "AndroidPay": False,
                "WalletType": "",
                "TotalFee": 0
            },
            "Success": True,
            "Message": None
        },
        200
    )
]

PREPARED_PARAMS = {
    "PublicId": "your_public_id",
    "Amount": 100,
    "Currency": "RUB",
    "Description": "A basket of oranges",
    "CardCryptogramPacket": "\"{\\\"type\\\":\\\"Yandex\\\",\\\"signedMessage\\\":\\\"{\\\\\\\"encryptedMessage\\\\\\\":\\\\\\\"xqpAiS2L71BZNgH514AQDwOVawJF4gHXF8P+ECIFRqFHlDMRtxHsO9hNQSeegSssRdDMlBIyOObY5dqI3iwX99UKYP6qFD+tKEYJQkUdiKyhZCwgUsVdHBlFQA+iiXVLf7DZ5WCIaHjpl4mckrGeDg4XGDIX4FB0BorLqocbDLcl0JZi2zzkNtn9FDLPSAs1qbTEMdb3TAS0iDAIkuAy5DGJ3+4Av9PWvIllW4LRdQ34rR8MPszJxq9Xagw/jeKUglyUERQgi5cnVWIB992yPh9UFgNuCQBc+JWLMzuOIKKxFiVK6VBSsuHpDWrSZqMolN6PIeNvETxQ34g+O/u4KiwWd3IG/pb5e0FYbzn/gWzlDSPsqNSuB713qZDHCI7eFB7h7iPTdk/Wd78Vv7Vlg4oVQdMWCbgSjtWDamKeq/OMiVDW5j36CebRQWxB8/XFj4nAInHIjoUUKsEQ5gf00n9/48RUNVCbRr6qykvsfnD0XP5V4OJOeIhAZN2CAgGxgrGC5MibfjAf+D/EnunHwOvtmI6KQAsGv9QgrRC8sxTeyk7OT9vUCzK2DIRDYyCtvloGalRq1PRdJWQX\\\\\\\",\\\\\\\"tag\\\\\\\":\\\\\\\"LTx6/HA9iWaZwbYaFN1j9aDOPp2PBlR2iBMUBQ7zyUg=\\\\\\\",\\\\\\\"ephemeralPublicKey\\\\\\\":\\\\\\\"BHHBcT4SvFgxMK14Oz3/dk/uiCL2m4jeTFDEcoYHXt5gAz2wFVEnvRD4fHArkbIOcry9nlUYHWgT4GicEl9qkXY=\\\\\\\"}\\\",\\\"protocolVersion\\\":\\\"ECv2\\\",\\\"signature\\\":\\\"MEUCICyyzWnCEf2iHlUszDzvbAx/qk/sLmbTaOWPVEq1hr29AiEA0lfZ85pCofYhxVX971Xtshysawi7+KEe8ZpPVlV/Md4=\\\",\\\"intermediateSigningKey\\\":{\\\"signedKey\\\":\\\"{\\\\\\\"keyValue\\\\\\\":\\\\\\\"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEqYNePt6BPgCv5JxfO9dF2vrSqmnp4Mhe/vF+XO+Devbs6/KVpVVoTD8LLcAo4TZh6IuODVnVpHrTObhg3HJVJA==\\\\\\\",\\\\\\\"keyExpiration\\\\\\\":\\\\\\\"1764950892000\\\\\\\"}\\\",\\\"signatures\\\":[\\\"MEQCIDRslMW7wNZbpqVw/dD7hDQh30hGhqfjfWTBvc7zAYJSAiAGAvjAslA2AxwdAEuOfacFr6DaE5yiiUuUtM6DUreZYg==\\\"]}}\"",
    "IpAddress": '127.0.0.1',
}
